version: '2'
run:
    timeout: 5m
    go: '1.22'

linters:
    enable:
        # Default linters
        - govet             # Vet examines Go source code and reports suspicious constructs
        - ineffassign       # Detects when assignments to existing variables are not used
        
        # Additional useful linters  
        - bodyclose         # Checks whether HTTP response body is closed successfully
        - errname           # Checks that sentinel errors are prefixed with Err
        - errorlint         # Find code that can cause problems with error wrapping
        - misspell          # Finds commonly misspelled English words in comments
    
    # Disabled for baseline - enable gradually as issues are fixed
    disable:
        - errcheck          # 36 issues - unchecked errors (mostly defer Close())
        - staticcheck       # 7 issues - style and deprecated API
        - unused            # 2 issues - unused functions
        - contextcheck      # 1 issue - non-inherited context
        - noctx             # 34 issues - DB calls without context
        - unparam           # 1 issue - unused param
        - gosec             # 22 issues - security (mostly false positives for baseline)

linters-settings:
    govet:
        enable-all: true
    gosec:
        excludes-generated: true

issues:
    # Maximum issues count per one linter. Set to 0 to disable.
    max-issues-per-linter: 0
    
    # Maximum count of issues with the same text. Set to 0 to disable.
    max-same-issues: 0
    
    # Baseline: Suppress existing gosec issues to achieve clean build
    # TODO: Gradually fix these issues and remove exclusions
    exclude:
        - "G101.*Potential hardcoded credentials"
        - "G104.*Errors unhandled"
        - "G204.*Subprocess launched with variable"
        - "G301.*Expect directory permissions"
        - "G304.*Potential file inclusion via variable"
        - "G404.*Use of weak random number generator"
    
    exclude-rules:
        # Exclude gosec from test files
        - path: _test\.go
          linters:
              - gosec
