{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vod-tender.fullname" . }}-api-policy
  labels:
    {{- include "vod-tender.api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vod-tender.api.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from frontend
  - from:
    - podSelector:
        matchLabels:
          {{- include "vod-tender.frontend.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  # Allow from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow to Postgres
  {{- if .Values.postgres.enabled }}
  - to:
    - podSelector:
        matchLabels:
          {{- include "vod-tender.postgres.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow external HTTPS (Twitch API, YouTube API)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vod-tender.fullname" . }}-frontend-policy
  labels:
    {{- include "vod-tender.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vod-tender.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
  egress:
  # Allow to API
  - to:
    - podSelector:
        matchLabels:
          {{- include "vod-tender.api.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53

{{- if .Values.postgres.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vod-tender.fullname" . }}-postgres-policy
  labels:
    {{- include "vod-tender.postgres.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vod-tender.postgres.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow from API only
  - from:
    - podSelector:
        matchLabels:
          {{- include "vod-tender.api.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432
  egress:
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
{{- end }}
{{- end }}
