{{- if .Values.secrets.create }}
{{- $twitchRedirectUri := .Values.secrets.twitch.redirectUri }}
{{- if not $twitchRedirectUri }}
{{- $twitchRedirectUri = printf "https://%s/auth/twitch/callback" .Values.ingress.api.host }}
{{- end }}
{{- $ytRedirectUri := .Values.secrets.youtube.redirectUri }}
{{- if not $ytRedirectUri }}
{{- $ytRedirectUri = printf "https://%s/auth/youtube/callback" .Values.ingress.api.host }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vod-tender.fullname" . }}-secrets
  labels:
    {{- include "vod-tender.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-dsn: {{ include "vod-tender.dbDsn" . | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  twitch-client-id: {{ .Values.secrets.twitch.clientId | quote }}
  twitch-client-secret: {{ .Values.secrets.twitch.clientSecret | quote }}
  twitch-oauth-token: {{ .Values.secrets.twitch.oauthToken | quote }}
  twitch-redirect-uri: {{ $twitchRedirectUri | quote }}
  twitch-scopes: {{ .Values.secrets.twitch.scopes | quote }}
  yt-client-id: {{ .Values.secrets.youtube.clientId | quote }}
  yt-client-secret: {{ .Values.secrets.youtube.clientSecret | quote }}
  yt-redirect-uri: {{ $ytRedirectUri | quote }}
  yt-scopes: {{ .Values.secrets.youtube.scopes | quote }}
{{- end }}
