{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vod-tender.fullname" . }}-secrets
  labels:
    {{- include "vod-tender.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-dsn: {{ include "vod-tender.dbDsn" . | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  twitch-client-id: {{ .Values.secrets.twitch.clientId | quote }}
  twitch-client-secret: {{ .Values.secrets.twitch.clientSecret | quote }}
  twitch-oauth-token: {{ .Values.secrets.twitch.oauthToken | quote }}
  twitch-redirect-uri: {{ .Values.secrets.twitch.redirectUri | quote }}
  twitch-scopes: {{ .Values.secrets.twitch.scopes | quote }}
  yt-client-id: {{ .Values.secrets.youtube.clientId | quote }}
  yt-client-secret: {{ .Values.secrets.youtube.clientSecret | quote }}
  yt-redirect-uri: {{ .Values.secrets.youtube.redirectUri | quote }}
  yt-scopes: {{ .Values.secrets.youtube.scopes | quote }}
{{- end }}
