name: Bug Report
description: Report a bug or unexpected behavior in vod-tender
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start service with `make up`
        2. Navigate to...
        3. Click on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: If applicable, add logs or screenshots to help explain your problem
      placeholder: Paste logs or drag and drop screenshots here...
      render: shell

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running vod-tender?
      options:
        - Docker Compose
        - Kubernetes
        - Local (Go binary)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of vod-tender are you running? (git commit SHA, Docker tag, or release version)
      placeholder: e.g., v1.2.3, main@abc1234, latest

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        - OS: Ubuntu 22.04
        - Go version: 1.21.0
        - Docker version: 24.0.5
        - PostgreSQL version: 14
        - yt-dlp version: 2023.10.13
      render: markdown

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove any secrets!)
      placeholder: |
        CHAT_AUTO_START=1
        LOG_LEVEL=debug
        CIRCUIT_FAILURE_THRESHOLD=5
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have removed any sensitive information (credentials, tokens, etc.)
          required: true
