apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vod-tender

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      environment: production
