apiVersion: v1
kind: ConfigMap
metadata:
  name: vod-tender-config
  namespace: vod-tender
  labels:
    app: vod-tender
data:
  # Twitch configuration
  TWITCH_CHANNEL: "your_channel_name"
  TWITCH_BOT_USERNAME: "your_bot_username"
  
  # Feature toggles
  CHAT_AUTO_START: "1"
  
  # Processing configuration
  VOD_CATALOG_BACKFILL_INTERVAL: "6h"
  VOD_PROCESS_INTERVAL: "1m"
  PROCESSING_RETRY_COOLDOWN: "600"
  
  # Download configuration
  DOWNLOAD_MAX_ATTEMPTS: "5"
  DOWNLOAD_BACKOFF_BASE: "2s"
  UPLOAD_MAX_ATTEMPTS: "5"
  UPLOAD_BACKOFF_BASE: "2s"
  
  # Circuit breaker
  CIRCUIT_OPEN_COOLDOWN: "5m"
  
  # Storage
  DATA_DIR: "/data"
  
  # Backfill settings
  BACKFILL_AUTOCLEAN: "1"
  RETAIN_KEEP_NEWER_THAN_DAYS: "7"
  BACKFILL_UPLOAD_DAILY_LIMIT: "10"
  
  # Chat auto settings
  CHAT_AUTO_POLL_INTERVAL: "30s"
  VOD_RECONCILE_DELAY: "1m"
