apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vod-tender

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres-statefulset.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml
  - networkpolicy.yaml
