apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vod-tender-staging

resources:
  - ../../base

namePrefix: staging-

labels:
  - pairs:
      environment: staging

patches:
  # Moderate data PVC size for staging
  - target:
      kind: PersistentVolumeClaim
      name: vod-tender-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi
  
  # Moderate postgres PVC size for staging
  - target:
      kind: StatefulSet
      name: postgres
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi
